### ISSUE TITLE
Demo is broken: `TypeError: Fetch API cannot load: REPLACE_HERE`

### ISSUE THREAD

**Issue by parasj** [upstash/waiting-room#4]
Upon visiting https://waiting-room.upsdev.workers.dev/, I see:
```
TypeError: Fetch API cannot load: REPLACE_HERE
    at baseUrl.request (worker.js:7:22465)
    at m.exec (worker.js:7:2343)
    at ut.dbsize (worker.js:7:16871)
    at worker.js:7:23420
    at worker.js:7:23650
```

**Comment by karlfrankeser** [comment]
rip
